### ISSUE TITLE
How to encrypt and save shares of a pretrained pytorch model?

### ISSUE THREAD

**Issue by w601sxs** [facebookresearch/CrypTen#238] opened 2021-03-25 00:51 UTC
Hi,

Please forgive my lack of deep understanding on the topic..........

I am trying to load a pretrained torch model, encrypt using crypten and save parts of the model using something like this:

First I encrypt the model and verify it is encrypted, then I would like to save the model:

```
@mpc.run_multiprocess(world_size=2)
def save_encrypted_model(model):
    # Save features, labels for Data Labeling example
    rank = comm.get().get_rank()
    crypten.save_from_party(private_model, f'private_model.encrypted.{rank}', src=rank)
```

Private model above is already encrypted. First of all, is this the correct way to save it?

Do I need to encrypt with a world size>1, or world size = 1? (see update below)

Do I save one file from a single rank? Or multiple files from multiple ranks like above. If I do, how do I reload the model?

Thanks

### Update:

When I try encrypting with a share like this:

```
@mpc.run_multiprocess(world_size=2)
def create_model_shares(model):
    rank = comm.get().get_rank()
    model.encrypt(src=rank)
        
create_model_shares(private_model)
```

And then try to view a particular layer's encrypted MPC tensor value according to rank, I get:

```
Rank 0:
 MPCTensor(
	_tensor=tensor([ 15078,  16867,      0, -41953,      0,  10576,  30083,      0,  19777,
             0,  22494,  20096, -15800,     -2,   7024,  14254,  24308, -36044,
        -41872,  37914,  20004,  37636,  32006,  21770,  12858,  12557,  10062,
          6427,  32524,   1640,  10788,  21414,  16931,  29099, -19852,  -1316,
             0,  20762,      0,  15416,  15369,  20442,  28396,  18902,  16951,
         45435,  27650,  22283,      0,  16446,  19953,  40853,  25514,  21493,
        -26507,  25037,  11895,  16515, -28068,  14005,  37782,  36900, -25656,
         15519])
	plain_text=HIDDEN
	ptype=ptype.arithmetic
)

Rank 1:
 MPCTensor(
	_tensor=tensor([ 15078,  16867,      0, -41953,      0,  10576,  30083,      0,  19777,
             0,  22494,  20096, -15800,     -2,   7024,  14254,  24308, -36044,
        -41872,  37914,  20004,  37636,  32006,  21770,  12858,  12557,  10062,
          6427,  32524,   1640,  10788,  21414,  16931,  29099, -19852,  -1316,
             0,  20762,      0,  15416,  15369,  20442,  28396,  18902,  16951,
         45435,  27650,  22283,      0,  16446,  19953,  40853,  25514,  21493,
        -26507,  25037,  11895,  16515, -28068,  14005,  37782,  36900, -25656,
         15519])
	plain_text=HIDDEN
	ptype=ptype.arithmetic
)
```

Arent't each of those numbers supposed to be different?

**Comment by w601sxs** [comment] 2021-03-25 14:16
Having the load and encrypt inside a function decorated by @mpc... also gives the same numbers as output:

```
@mpc.run_multiprocess(world_size=2)
def create_model_shares(model):
    private_model = crypten.nn.from_pytorch(model, dummy_input)
    rank = comm.get().get_rank()
    private_model.encrypt(src=rank)
        
create_model_shares(model)
```

**Comment by w601sxs** [comment] 2021-03-31 19:51
Any pointers here are appreciated Crypten team ........... :D

**Comment by lvdmaaten** [comment] 2021-04-01 11:46
In the second part of your question, I suspect the problem is that you are doing `private_model.encrypt(src=rank)` with `rank` being the rank of the party executing the code. The `src` kwarg indicates which party is providing the plaintext values that need to be encrypted (default: party 0). What happens when you set `src=comm.get().get_rank()` is that you are telling party 0 that they will be providing the plaintext values, but you're telling party 1 that they will be providing the plaintext values. I am unsure what behavior that leads to, but I can imagine that it leads to both parties having the same share due to the way that PRZS works. Does setting `model.encrypt(src=0)` or `model.encrypt(src=1)` lead tot he shares that you would expect?

As for `save_from_party`, I always get confused about this myself :) and am unconvinced it should exist. Doesn't `crypten.save(private_model.state_dict(), f"private_model.encrypted.{rank}")` do what you need? @knottb may understand this bit better than me.

**Comment by w601sxs** [comment] 2021-04-07 16:43
Thanks @lvdmaaten 

That makes sense (re: passing rank as src). 

> Does setting model.encrypt(src=0) or model.encrypt(src=1) lead tot he shares that you would expect?

I can confirm that when I do this, I have `private_model.encrypted = True`

However, after I do this and check the share on different workers using `private_model.state_dict()`, I still get exactly the same share.

As mentioned earlier, when encrypt is done within a multiprocess with world size>1, even with the  same source, the resulting shares looks the same. 

```
@mpc.run_multiprocess(world_size=2)
def create_model_shares(model):
    private_model = crypten.nn.from_pytorch(model, dummy_input)
    rank = comm.get().get_rank()
    private_model.encrypt(src=L4V_SERVICE_MODEL_SOURCE)
```

**Comment by w601sxs** [comment] 2021-04-07 17:52
It may have to do with printing the shares so I tried

1. `crypten.print(f"\nRank {rank}:\n {model.state_dict()['192.weight']}\n", in_order=True)
`
and

2. `crypten.print(f"\nRank {rank}:\n {model.state_dict()['192.weight']._tensor}\n", in_order=True)`


both give me this error

```
AttributeError: 'dict' object has no attribute 'print'
AttributeError: 'dict' object has no attribute 'print'
ERROR:root:One of the parties failed. Check past logs
```

**Comment by knottb** [comment] 2021-04-09 19:11
Regarding your print error - This was an intermittent error in our code that should have been fixed in a recent PR (due to some strange behavior of Python's `builtins` module). Try `git pull`ing to get the most recent changes.

Regarding the loading issues, using [`crypten.save()`](https://github.com/facebookresearch/CrypTen/blob/master/crypten/__init__.py#L372-L386) and [`crypten.load()`](https://github.com/facebookresearch/CrypTen/blob/master/crypten/__init__.py#L325-L341) should be exactly like saving and loading from PyTorch using `torch.save()` and `torch.load()`, with the exception that filenames must be different on each party (otherwise they could overwrite each other if using the same machine). 

Because we need to serialize the model parameters in order to save, we need to work with model `state_dict`s rather than saving the model itself, as is done in PyTorch. See [PyTorch's tutorial](https://pytorch.org/tutorials/beginner/saving_loading_models.html) for how this should be handled.

**Closed** 2021-07-14 18:08 UTC
Labels: question
