### ISSUE TITLE
A question about model encryption

### ISSUE THREAD

**Issue by MtifyC** [facebookresearch/CrypTen#280] opened 2021-07-01 17:11 UTC
##  Feature

With Tutorials I learn that we will need to work with encrypted data and encrypted models.The process of encrypting the data is also detailed: it is essentially done by two secret sharing protocols, which split the data into N pieces and send them to N parties.
My question is is it necessary to encrypt the model? What are the rules of encrypting the model? How does it do it?

## Alternatives

I guess whether the split of the data and the split of the model have to be consistent, i.e. they have to perform the same encryption before they can be run together?But how is that guaranteed, or am I wrong?

**Comment by knottb** [comment] 2021-07-07 20:59
This is a duplicate of https://github.com/facebookresearch/CrypTen/issues/279. Closing.

**Closed by knottb** 2021-07-07 20:59 UTC
