### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by st1064870** [facebookresearch/CrypTen#382] opened 2022-05-22 20:04 UTC
When trying to run the `examples/mpc_autograd_cnn/launcher.py` or  `examples/mpc_linear_svm/launcher.py` I get the following error :

```
TypeError: 'float' object cannot be interpreted as an integer
```

I can provide more details and stack trace if needed.

**Comment by knottb** [comment] 2022-05-23 20:12
Also could you provide the command you are using to launch the script?

**Comment by YZY010203** [comment] 2022-08-19 12:50
Sorry, I meet the same question like this.Thank you for your time.
![图片](https://user-images.githubusercontent.com/63569612/185622014-e55462e6-e3c4-4094-8f7f-130613df3d8e.png)

**Comment by gcormode** [comment] 2022-08-23 10:26
Can you try using the div method instead of / operator?

**Comment by lvdmaaten** [comment] 2022-08-23 12:40
That shouldn't matter because both function should execute [the same code path](https://github.com/facebookresearch/CrypTen/blob/main/crypten/cryptensor.py#L143), but you never know.

Anyway... I cannot reproduce this using the current version of CrypTen (installed from source). Can you try and `git clone` the repo, use `pip install -e .` to install, and see if the issue persists? What version of PyTorch are you using? Does it matter if you update to PyTorch 1.12?

**Comment by YZY010203** [comment] 2022-08-23 15:00
Thank you very much. The error has disappeared by reinstall.

**Comment by st1064870** [comment] 2022-08-25 15:41
I will try to reproduce the issue again later, if I cannot you can close the issue.

**Comment by lvdmaaten** [comment] 2022-08-25 15:52
Just as FYI: @YZY010203 reported the same issue [here](https://github.com/facebookresearch/CrypTen/issues/395) and for them it appears to have been resolved by updated to the latest version of CrypTen (installing from source). I hope the same works for you, @st1064870!

**Closed** 2022-12-08 02:42 UTC
